"""
WC2026 remaining group stage fixtures — AUTO-GENERATED by sync.py
Source: https://raw.githubusercontent.com/openfootball/worldcup.json/master/2026/worldcup.json
Last synced: 2026-06-23 21:55 UTC
"""
from __future__ import annotations
from dataclasses import dataclass

@dataclass(frozen=True)
class Fixture:
    date: str
    group: str
    home: str
    away: str

REMAINING_FIXTURES: list[Fixture] = [
    Fixture("2026-06-23", "K", "Colombia", "DR Congo"),
    Fixture("2026-06-23", "L", "England", "Ghana"),
    Fixture("2026-06-23", "L", "Panama", "Croatia"),
    Fixture("2026-06-24", "A", "Czechia", "Mexico"),
    Fixture("2026-06-24", "A", "South Africa", "South Korea"),
    Fixture("2026-06-24", "B", "Bosnia and Herzegovina", "Qatar"),
    Fixture("2026-06-24", "B", "Switzerland", "Canada"),
    Fixture("2026-06-24", "C", "Morocco", "Haiti"),
    Fixture("2026-06-24", "C", "Scotland", "Brazil"),
    Fixture("2026-06-25", "D", "Paraguay", "Australia"),
    Fixture("2026-06-25", "D", "Turkiye", "United States"),
    Fixture("2026-06-25", "E", "Curacao", "Ivory Coast"),
    Fixture("2026-06-25", "E", "Ecuador", "Germany"),
    Fixture("2026-06-25", "F", "Japan", "Sweden"),
    Fixture("2026-06-25", "F", "Tunisia", "Netherlands"),
    Fixture("2026-06-26", "G", "Egypt", "Iran"),
    Fixture("2026-06-26", "G", "New Zealand", "Belgium"),
    Fixture("2026-06-26", "H", "Cape Verde", "Saudi Arabia"),
    Fixture("2026-06-26", "H", "Uruguay", "Spain"),
    Fixture("2026-06-26", "I", "Norway", "France"),
    Fixture("2026-06-26", "I", "Senegal", "Iraq"),
    Fixture("2026-06-27", "J", "Algeria", "Austria"),
    Fixture("2026-06-27", "J", "Jordan", "Argentina"),
    Fixture("2026-06-27", "K", "Colombia", "Portugal"),
    Fixture("2026-06-27", "K", "DR Congo", "Uzbekistan"),
    Fixture("2026-06-27", "L", "Croatia", "Ghana"),
    Fixture("2026-06-27", "L", "Panama", "England"),
]
