"""
Tournament probabilities endpoint.

Serves the precomputed Monte Carlo output (data/processed/tournament_probabilities.json)
generated by src/simulation/monte_carlo.py. This is STATIC data — it does
not recompute on every request, since running 10,000 simulations per HTTP
call would be far too slow. The file must be regenerated periodically by
re-running monte_carlo.py as the real tournament progresses (see that
module's docstring for the maintenance note).
"""

from __future__ import annotations
import json
from pathlib import Path
from fastapi import APIRouter

router = APIRouter(prefix="/tournament", tags=["tournament"])

PROBABILITIES_PATH = Path("data/processed/tournament_probabilities.json")


def _load_probabilities() -> dict:
    if not PROBABILITIES_PATH.exists():
        return {"error": "Tournament probabilities not yet generated. Run src/simulation/monte_carlo.py first."}
    with open(PROBABILITIES_PATH) as f:
        return json.load(f)


@router.get("/probabilities")
def get_tournament_probabilities():
    """Returns full per-team probabilities: champion%, final%, SF%, QF%, R32%."""
    return _load_probabilities()


@router.get("/contenders")
def get_top_contenders(limit: int = 10):
    """Returns the top N teams ranked by championship probability."""
    data = _load_probabilities()
    if "error" in data:
        return data

    sorted_teams = sorted(
        data["probabilities"].items(),
        key=lambda kv: kv[1]["champion_pct"],
        reverse=True,
    )
    return {
        "n_simulations": data["n_simulations"],
        "generated_at": data["generated_at"],
        "top_contenders": [
            {"team": team, **stats} for team, stats in sorted_teams[:limit]
        ],
    }